version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cargo-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dbm7rj5asjvs"
s3_prefix = "cargo-local"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
